#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# IMPORT GENERIC HELPERS
source /usr/share/yunohost/helpers

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

# Import common cmd
source ./experimental_helper.sh
source ./_common.sh

ynh_script_progression --message="Loading installation settings..."

# RETRIEVE ARGUMENTS
old_domain=$YNH_APP_OLD_DOMAIN
domain=$YNH_APP_NEW_DOMAIN
path_url=$(ynh_normalize_url_path --path_url ${YNH_APP_NEW_PATH:-'/'})
app=$YNH_APP_INSTANCE_NAME

admin=$(ynh_app_setting_get --app $app --key admin)
final_path=$(ynh_app_setting_get --app $app --key final_path)
port=$(ynh_app_setting_get --app $app --key port)
secret_key=$(ynh_app_setting_get --app $app --key secret_key)
service_autodiscovery=$(ynh_app_setting_get --app $app --key service_autodiscovery)
db_name=$(ynh_app_setting_get --app $app --key db_name)
db_user=$(ynh_app_setting_get --app $app --key db_user)
db_pwd=$(ynh_app_setting_get --app $app --key mysqlpwd)

#=================================================
# STANDARD MODIFICATIONS
#=================================================

ynh_script_progression --message="Updating nginx configuration..."

# MODIFY URL IN NGINX CONF
nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf

# Change the domain for nginx
if [ "$old_domain" != "$domain" ]
then
    # Delete file checksum for the old conf file location
    ynh_delete_file_checksum --file "$nginx_conf_path"
    mv $nginx_conf_path /etc/nginx/conf.d/$domain.d/$app.conf
    # Store file checksum for the new config file location
    ynh_store_file_checksum --file "/etc/nginx/conf.d/$domain.d/$app.conf"
fi

config_nginx

# Update horde config
ynh_script_progression --message="Configuring application..." --weight=3
config_horde

# RELOAD NGINX
systemctl reload nginx

ynh_script_progression --message="Change of URL completed for $app" --last
