#!/bin/bash

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
ynh_abort_if_errors

# Import common cmd
source ../settings/scripts/experimental_helper.sh
source ../settings/scripts/_common.sh

# LOAD SETTINGS
app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)
final_path=$(ynh_app_setting_get $app final_path)
db_name=$(ynh_app_setting_get $app db_name)

# CHECK IF THE APP CAN BE RESTORED
ynh_webpath_available $domain $path_url \
	|| ynh_die "Path not available: ${domain}${path_url}"
test ! -d $final_path \
	|| ynh_die "There is already a directory: $final_path "

# Define and install dependencies
install_dependance

# Create the dedicated user (if not existing)
ynh_system_user_create $app

# Restore all config and data
ynh_restore

# RESTORE THE MYSQL DATABASE
db_pwd=$(ynh_app_setting_get $app mysqlpwd)
ynh_mysql_setup_db $db_name $db_name $db_pwd
ynh_mysql_connect_as $db_name $db_pwd $db_name < ./db.sql

# SECURE FILES AND DIRECTORIES
set_permission

# SETUP LOGROTATE
ynh_use_logrotate $final_path/horde
ynh_use_logrotate $final_path/horde/services
ynh_use_logrotate $final_path/horde/services/portal

# Reload services
systemctl reload php5-fpm
systemctl reload nginx
